name       : font-jetbrainsmono-ttf
version    : '2.304'
release    : 11
source     :
    - https://github.com/JetBrains/JetBrainsMono/releases/download/v2.304/JetBrainsMono-2.304.zip : 6f6376c6ed2960ea8a963cd7387ec9d76e3f629125bc33d1fdcd7eb7012f7bbf
license    : OFL-1.1
component  : desktop.font
homepage   : https://www.jetbrains.com/lp/mono/
summary    : A free and open-source typeface for developers
description: |
    JetBrains Mono is a free and open-source monospace font from JetBrains, designed for developers. Like Fira Code, it features over a hundred code-specific ligatures, with support for over 140 languages.
install    : |
    install -Dm00644 fonts/ttf/*.ttf -t $installdir/usr/share/fonts/truetype/jetbrainsmono/
