name       : font-jetbrainsmono-ttf
version    : '2.210'
release    : 7
source     :
    - https://github.com/JetBrains/JetBrainsMono/archive/v2.210.tar.gz : ee67e87880dc1a5931b49a479f102f343cbbe5bb9f8bab04aa2b15041fb7c187
license    : OFL-1.1
component  : desktop.font
homepage   : https://www.jetbrains.com/lp/mono/
summary    : A free and open-source typeface for developers
description: |
    JetBrains Mono is a free and open-source monospace font from JetBrains, designed for developers. Like Fira Code, it features over a hundred code-specific ligatures, with support for over 140 languages.
install    : |
    install -Dm00644 fonts/ttf/*.ttf -t $installdir/usr/share/fonts/truetype/jetbrainsmono/
