name       : font-jetbrainsmono-ttf
version    : 1.0.6
release    : 2
source     :
    - https://github.com/JetBrains/JetBrainsMono/archive/v1.0.6.tar.gz : c2f3a7c063659d9d8414a1b8c38471723c2f3a97d24fdae32c450db7811ade02
license    : Apache-2.0
component  : desktop.font
summary    : A free and open-source typeface for developers
description: |
    JetBrains Mono is a free and open-source monospace font from JetBrains, designed for developers. Like Fira Code, it features over a hundred code-specific ligatures, with support for over 140 languages. More information can be found on its dedicated webpage [here](https://www.jetbrains.com/lp/mono/).
install    : |
    install -Dm00644 ttf/*.ttf -t $installdir/usr/share/fonts/truetype/jetbrainsmono/
