name       : font-jetbrainsmono-ttf
version    : '2.221'
release    : 8
source     :
    - https://github.com/JetBrains/JetBrainsMono/releases/download/v2.221/JetBrainsMono-2.221.zip : 2fcbc70aca5ddabcfdbbc536c2b5f65ccf798ff13d8078738cbbef84c57e99a9
license    : OFL-1.1
component  : desktop.font
homepage   : https://www.jetbrains.com/lp/mono/
summary    : A free and open-source typeface for developers
description: |
    JetBrains Mono is a free and open-source monospace font from JetBrains, designed for developers. Like Fira Code, it features over a hundred code-specific ligatures, with support for over 140 languages.
install    : |
    install -Dm00644 fonts/ttf/*.ttf -t $installdir/usr/share/fonts/truetype/jetbrainsmono/
