name       : font-jetbrainsmono-ttf
version    : '2.200'
release    : 6
source     :
    - https://github.com/JetBrains/JetBrainsMono/archive/v2.200.tar.gz : d7a321832c87c515aeccfd6bfe32ba622a252448e36cb3df6b96822299143546
license    : OFL-1.1
component  : desktop.font
homepage   : https://www.jetbrains.com/lp/mono/
summary    : A free and open-source typeface for developers
description: |
    JetBrains Mono is a free and open-source monospace font from JetBrains, designed for developers. Like Fira Code, it features over a hundred code-specific ligatures, with support for over 140 languages.
install    : |
    install -Dm00644 fonts/ttf/*.ttf -t $installdir/usr/share/fonts/truetype/jetbrainsmono/
