name       : font-jetbrainsmono-ttf
version    : 1.0.5
release    : 1
source     :
    - https://github.com/JetBrains/JetBrainsMono/archive/v1.0.5.tar.gz : e902b830d6d3c2054493b0b1fe64d1d88600eda61794d9aa1d3ebb12ec9a5307
license    : Apache-2.0
component  : desktop.font
summary    : A free and open-source typeface for developers
description: |
    JetBrains Mono is a free and open-source monospace font from JetBrains, designed for developers. Like Fira Code, it features over a hundred code-specific ligatures, with support for over 140 languages. More information can be found on its dedicated webpage [here](https://www.jetbrains.com/lp/mono/).
install    : |
    install -Dm00644 ttf/*.ttf -t $installdir/usr/share/fonts/truetype/jetbrainsmono/
